# Generated by Django 4.2.4 on 2023-08-16 12:10

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('register_duration_time', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('game_duration_time', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('picture', models.TextField()),
                ('user_limit', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('rate', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reservestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField()),
                ('status', models.IntegerField()),
                ('event_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('picture', models.TextField()),
                ('link', models.TextField()),
                ('order', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
