# Generated by Django 4.2.4 on 2023-08-22 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservestion',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='reservestion',
            name='user_id',
        ),
        migrations.AddField(
            model_name='reservestion',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservestion',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='slider',
            name='link',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='slider',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
