# Generated by Django 4.2.3 on 2023-08-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('role', models.IntegerField(choices=[(1, 'مدیر'), (2, 'برنامه نویس فرانت'), (3, 'برنامه نویس بک اند')])),
                ('picture', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
