# Generated by Django 4.2.4 on 2023-08-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='icon',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='link',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
