# Generated by Django 4.2.4 on 2023-09-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_alter_socialmedia_icon_alter_socialmedia_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='icon',
            field=models.FileField(upload_to=''),
        ),
    ]
