# Generated by Django 4.2.4 on 2023-09-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0003_alter_socialmedia_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('picture', models.ImageField(upload_to='')),
                ('link', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='role',
            field=models.IntegerField(choices=[(1, 'Manager'), (2, 'Front-End programmer'), (3, 'Back-End programmer')]),
        ),
    ]
