# Generated by Django 4.2.4 on 2023-09-03 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0004_sliderlanding_alter_teammembers_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderlanding',
            name='title',
        ),
    ]
