# Generated by Django 4.2.4 on 2023-08-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_games_company_id_games_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(),
        ),
    ]
